#%RAML 0.8
title: Example RAML
mediaType: application/json
documentation:
  - title: Interns at XYZ company
    content: My first raml api!!!... List interns by name and title
/interns:
  description: Listing interns.
  get:
    description: Listing all interns.
    responses:
        200:
          body:
            example: |
              [{ "id": 1, "name": "Kumaran","title": "Software Engineer intern"}]
  post:
    description: Creating a new intern
    body:
      example: |
        { "name": "internName", "title": "internTitle"}
    headers:
    responses:
      201:
        body:
          example: |
            {
            "id": 1,
            "name": "internName",
            "title": "internTitle"
            }

  /{id}:
    description: A specific intern tracked by id
    uriParameters:
      id:
        description: the `id` of intern.
        type: number
        example: 1
    get:
      description: Retrieve specified intern
      responses:
        200:
          body:
            example: |
              {
              "id": 2,
              "name": "Kumaran",
              "title": "Software Engineer Intern"
              }
    patch:
        description: Update intern information
        body:
          example: |
            {
            "name": "newName",
            "title": "newTitle"
            }
        responses:
          200:
            body:
              example: |
                {
                "name": "Kumaran",
                "title": "CEO"
                }
    delete:
          description: Remove intern
          responses:
            204:
